### ISSUE TITLE
Why can't the drone fly upwards

### ISSUE THREAD

**Issue by hcws** [Bottle101/Air-FAR#1]
![Selection_339](https://github.com/Bottle101/Air-FAR/assets/28213814/0ee23d25-a2a5-47c9-9939-bb96d009a1b6)

I set a 3D goal point, but it can't fly up.

**Comment by Bottle101** [comment]
Sry for the late reply. Because we constrained the velocity direction within the Perception range (Field of View) to ensure the safety. We will take this into path planning constraint soon.

**Comment by bairuofei** [comment]
Hi @Bottle101 , I also have the same issue. Currently the config [this line](https://github.com/Bottle101/Air-FAR/blob/f6cf0ad864c18bb78ceeb4440373a0b6dc7279f4/src/airfar_planner/config/default.yaml#L48) is not in use, right? Can we increase the vertical limitation of robots? For my application, seems the drone cannot directly fly upward to escape from a fence. Thanks for your help!

**Comment by Bottle101** [comment]
Hi Ruofei,

For the local planner part, This repo includes a generator.m to generate the paths: https://github.com/caochao39/aerial_navigation_development_environment/tree/melodic-noetic/src/local_planner/paths

If you just need to fly along the z-axis, I would suggest modifying the path_follower.cpp to directly send a /cmd_vel. If you need more than that, you can modify the generation code by yourself.

Let me know if you have any questions.

Best,
Botao

**Comment by bairuofei** [comment]
Thanks for your help! After generating new motion primitives, the drone can now fly to a higher target position more efficiently.
