### ISSUE TITLE
Migrate the program to my simulation environment，it failed!

### ISSUE THREAD

**Issue by hcws** [Bottle101/Air-FAR#3]
Thanks for your work!
I use `outdoor.yaml ` and only change **sensor_range** from 30 to 300
here is the  graph
![Selection_345](https://github.com/Bottle101/Air-FAR/assets/28213814/e2ecd09c-b962-41e5-8f38-3dadd7800865)
![Selection_346](https://github.com/Bottle101/Air-FAR/assets/28213814/2d3e4488-fd61-4da6-bee8-5f625075dc0c)

**Comment by Bottle101** [comment]
Hi, I don't know what it is in your first image, seems like it is not the visulization from FAR planner. 
For the second one, I guess you did not filter out the points far away in your simulation environment. For example, if your sensor is 30m, you need to filter out the points that have the distance larger than 29.9m or sth like that.

Let me know if it works for you!

**Comment by hcws** [comment]
Thanks for your replay! 
1. Picture One : It's the` /terrain_map_ext` cloud, in this image one grid is 10m 
2. Picture Two : one grid is 10m ,too . 
3. 30m in front of the origin is a large cube.
4. My lidar is only 70 degrees horizontal.
**Problem : Unable to establish the correct obstacle contour.**

**Comment by Bottle101** [comment]
is that possible for you to provide more information? Can you provide the visulization of your /registered_scan and snapshots of your environment? 

Please make sure you did the correct transformation between sensor frame, body frame and world frame.

**Comment by hcws** [comment]
> is that possible for you to provide more information? Can you provide the visulization of your /registered_scan and snapshots of your environment?
> 
> Please make sure you did the correct transformation between sensor frame, body frame and world frame.

Sorry,It's Hard to commit the simlator, It's a simple environment ,It only Contain One Cube and cylinders.
![image](https://github.com/Bottle101/Air-FAR/assets/28213814/eff5446d-5942-4f0b-a783-bfc2e13a903c)

1. Based on RVIZ, I see that the terrain point cloud and the registered point cloud are both in the correct positions.
2. My simulation environment is that there are very few obstacles and very few point clouds, which are all point clouds on the ground.

**When Drone Move:**
![image](https://github.com/Bottle101/Air-FAR/assets/28213814/12ca74d2-ebce-4aff-9d29-4d5c31a02f9a)
I feel the odom may not update.

**Comment by hcws** [comment]
Finally, I found that there was a problem with my point cloud conversion, which was finally solved. I am very sorry for the trouble。
![Selection_349](https://github.com/Bottle101/Air-FAR/assets/28213814/4baac6ba-820a-425a-bd30-500389312b2e)

**Comment by hcws** [comment]
**Finally, I found that there was a problem with my point cloud conversion, which was finally solved. 
I am very sorry for the trouble。**
![Selection_349](https://github.com/Bottle101/Air-FAR/assets/28213814/4baac6ba-820a-425a-bd30-500389312b2e)

**Comment by Bottle101** [comment]
Glad to hear that! If you found the V-graph not correct, you can set the save_contour as true in config file, and repleace the save_path with your local path to save the contour images. You can find if there is anything wrong with the extracted contour by doing so.
